services:
  - type: web
    name: citizen-report-backend
    runtime: python
    rootDir: backend
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PROJECT_NAME
        value: "Bangladesh Citizen Report Platform"
      - key: VERSION
        value: "0.1.0"
      - key: API_V1_STR
        value: "/api/v1"
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "10080"
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: '["https://frontend-ten-delta-a5irgspmf7.vercel.app", "https://frontend-kcdpp90wd-alfi-s-projects.vercel.app", "http://localhost:3000"]'
      - key: STORAGE_BACKEND
        value: local
      - key: STORAGE_BUCKET
        value: citizen-report-evidence-prod
