import asyncio
import logging
import uuid
from datetime import datetime, timezone
from typing import List, Dict, Any
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.db.session import async_session_factory
from app.models.emergency_service import EmergencyService, ServiceType, VerificationStatus

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("seed_emergency_services")

# Verified Official Directory Data
OFFICIAL_EMERGENCY_SERVICES: List[Dict[str, Any]] = [
    # --- DHAKA METROPOLITAN (DMP) POLICE STATIONS & POLICE BOXES ---
    {
        "name": "Dhanmondi Police Station",
        "name_bn": "ধানমন্ডি মডেল থানা",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Dhaka",
        "area": "Dhanmondi",
        "address": "House 51, Road 9/A, Dhanmondi R/A, Dhaka-1209",
        "address_bn": "বাড়ি ৫১, রোড ৯/এ, ধানমন্ডি আ/এ, ঢাকা-১২০৯",
        "phone": "+8802223362144",
        "alternate_phone": "+8801320037800",
        "latitude": 23.7461,
        "longitude": 90.3742,
        "source": "Dhaka Metropolitan Police (DMP) Official Directory",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Dhanmondi 27 Police Box",
        "name_bn": "ধানমন্ডি ২৭ নম্বর ট্রাফিক পুলিশ বক্স",
        "service_type": ServiceType.POLICE_BOX,
        "district": "Dhaka",
        "area": "Dhanmondi",
        "address": "Dhanmondi 27 Intersection (Mirpur Road), Dhaka",
        "address_bn": "ধানমন্ডি ২৭ নম্বর ইন্টারসেকশন (মিরপুর রোড), ঢাকা",
        "phone": "+8801320037810",
        "alternate_phone": "999",
        "latitude": 23.7538,
        "longitude": 90.3768,
        "source": "DMP Traffic South Division",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Shahbagh Police Station",
        "name_bn": "শাহবাগ থানা",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Dhaka",
        "area": "Shahbagh",
        "address": "Shahbagh Intersection, Ramna, Dhaka-1000",
        "address_bn": "শাহবাগ মোড়, রমনা, ঢাকা-১০০০",
        "phone": "+8802223381005",
        "alternate_phone": "+8801320037400",
        "latitude": 23.7383,
        "longitude": 90.3957,
        "source": "DMP Ramna Division",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "TSC Dhaka University Police Box",
        "name_bn": "টিএসসি ঢাকা বিশ্ববিদ্যালয় পুলিশ বক্স",
        "service_type": ServiceType.POLICE_BOX,
        "district": "Dhaka",
        "area": "Shahbagh",
        "address": "TSC Roundabout, Dhaka University Campus, Dhaka",
        "address_bn": "টিএসসি চত্বর, ঢাকা বিশ্ববিদ্যালয় ক্যাম্পাস, ঢাকা",
        "phone": "+8801320037415",
        "alternate_phone": "999",
        "latitude": 23.7317,
        "longitude": 90.3962,
        "source": "DMP Ramna Division",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Ramna Model Police Station",
        "name_bn": "রমনা মডেল থানা",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Dhaka",
        "area": "Ramna",
        "address": "Siddheswari Circular Road, Ramna, Dhaka-1217",
        "address_bn": "সিদ্ধেশ্বরী সার্কুলার রোড, রমনা, ঢাকা-১২১৭",
        "phone": "+8802223387877",
        "alternate_phone": "+8801320037300",
        "latitude": 23.7431,
        "longitude": 90.4079,
        "source": "DMP Official Directory",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Kakrail Traffic Police Box",
        "name_bn": "কাকরাইল মোড় পুলিশ বক্স",
        "service_type": ServiceType.POLICE_BOX,
        "district": "Dhaka",
        "area": "Ramna",
        "address": "Kakrail Mosque Intersection, VIP Road, Dhaka",
        "address_bn": "কাকরাইল মসজিদ মোড়, ভিআইপি রোড, ঢাকা",
        "phone": "+8801320037310",
        "alternate_phone": "999",
        "latitude": 23.7388,
        "longitude": 90.4071,
        "source": "DMP Traffic Division",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Gulshan Police Station",
        "name_bn": "গুলশান মডেল থানা",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Dhaka",
        "area": "Gulshan",
        "address": "House 1, Road 71, Gulshan-2, Dhaka-1212",
        "address_bn": "বাড়ি ১, রোড ৭১, গুলশান-২, ঢাকা-১২১২",
        "phone": "+8802222281488",
        "alternate_phone": "+8801320041400",
        "latitude": 23.7925,
        "longitude": 90.4152,
        "source": "DMP Gulshan Division",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Gulshan-1 Circle Police Box",
        "name_bn": "গুলশান-১ গোলচত্বর পুলিশ বক্স",
        "service_type": ServiceType.POLICE_BOX,
        "district": "Dhaka",
        "area": "Gulshan",
        "address": "Gulshan-1 Roundabout, Gulshan Avenue, Dhaka",
        "address_bn": "গুলশান-১ গোলচত্বর, গুলশান এভিনিউ, ঢাকা",
        "phone": "+8801320041415",
        "alternate_phone": "999",
        "latitude": 23.7786,
        "longitude": 90.4172,
        "source": "DMP Gulshan Traffic",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Banani Police Station",
        "name_bn": "বনানী থানা",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Dhaka",
        "area": "Banani",
        "address": "House 10, Road 11, Block F, Banani, Dhaka-1213",
        "address_bn": "বাড়ি ১০, রোড ১১, ব্লক এফ, বনানী, ঢাকা-১২১৩",
        "phone": "+8802222280200",
        "alternate_phone": "+8801320041600",
        "latitude": 23.7937,
        "longitude": 90.4046,
        "source": "DMP Gulshan Division",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Mirpur Model Police Station",
        "name_bn": "মিরপুর মডেল থানা",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Dhaka",
        "area": "Mirpur",
        "address": "Section 2, Mirpur, Dhaka-1216",
        "address_bn": "সেকশন ২, মিরপুর, ঢাকা-১২১৬",
        "phone": "+88029001000",
        "alternate_phone": "+8801320042600",
        "latitude": 23.8055,
        "longitude": 90.3639,
        "source": "DMP Mirpur Division",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Mirpur-10 Roundabout Police Box",
        "name_bn": "মিরপুর-১০ গোলচত্বর ট্রাফিক পুলিশ বক্স",
        "service_type": ServiceType.POLICE_BOX,
        "district": "Dhaka",
        "area": "Mirpur",
        "address": "Mirpur-10 Roundabout (Metro Station), Dhaka",
        "address_bn": "মিরপুর-১০ গোলচত্বর (মেট্রো স্টেশন সংলগ্ন), ঢাকা",
        "phone": "+8801320042615",
        "alternate_phone": "999",
        "latitude": 23.8069,
        "longitude": 90.3687,
        "source": "DMP Traffic West",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Uttara East Police Station",
        "name_bn": "উত্তরা পূর্ব থানা",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Dhaka",
        "area": "Uttara",
        "address": "Sector 4, Road 1, Uttara Model Town, Dhaka-1230",
        "address_bn": "সেক্টর ৪, রোড ১, উত্তরা মডেল টাউন, ঢাকা-১২৩০",
        "phone": "+88028956333",
        "alternate_phone": "+8801320043800",
        "latitude": 23.8681,
        "longitude": 90.3995,
        "source": "DMP Uttara Division",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Uttara House Building Police Box",
        "name_bn": "উত্তরা হাউস বিল্ডিং পুলিশ বক্স",
        "service_type": ServiceType.POLICE_BOX,
        "district": "Dhaka",
        "area": "Uttara",
        "address": "House Building Intersection, Dhaka-Mymensingh Highway, Uttara",
        "address_bn": "হাউস বিল্ডিং মোড়, ঢাকা-ময়মনসিংহ হাইওয়ে, উত্তরা",
        "phone": "+8801320043815",
        "alternate_phone": "999",
        "latitude": 23.8742,
        "longitude": 90.3986,
        "source": "DMP Traffic North",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Mohammadpur Police Station",
        "name_bn": "মোহাম্মদপুর থানা",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Dhaka",
        "area": "Mohammadpur",
        "address": "Tajmahal Road, Mohammadpur, Dhaka-1207",
        "address_bn": "তাজমহল রোড, মোহাম্মদপুর, ঢাকা-১২০৭",
        "phone": "+88029119966",
        "alternate_phone": "+8801320038200",
        "latitude": 23.7658,
        "longitude": 90.3627,
        "source": "DMP Tejgaon Division",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Tejgaon Police Station",
        "name_bn": "তেজগাঁও থানা",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Dhaka",
        "area": "Tejgaon",
        "address": "Tejgaon Industrial Area, Dhaka-1208",
        "address_bn": "তেজগাঁও শিল্প এলাকা, ঢাকা-১২০৮",
        "phone": "+88029118833",
        "alternate_phone": "+8801320038000",
        "latitude": 23.7597,
        "longitude": 90.3912,
        "source": "DMP Tejgaon Division",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Farmgate Police Box",
        "name_bn": "ফার্মগেট ট্রাফিক পুলিশ বক্স",
        "service_type": ServiceType.POLICE_BOX,
        "district": "Dhaka",
        "area": "Tejgaon",
        "address": "Farmgate Roundabout, Kazi Nazrul Islam Avenue, Dhaka",
        "address_bn": "ফার্মগেট চত্বর, কাজী নজরুল ইসলাম এভিনিউ, ঢাকা",
        "phone": "+8801320038015",
        "alternate_phone": "999",
        "latitude": 23.7570,
        "longitude": 90.3896,
        "source": "DMP Traffic",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Kotwali Police Station (Dhaka)",
        "name_bn": "কোতোয়ালী থানা (ঢাকা)",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Dhaka",
        "area": "Kotwali",
        "address": "Johnson Road, Old Dhaka, Dhaka-1100",
        "address_bn": "জনসন রোড, পুরান ঢাকা, ঢাকা-১১০০",
        "phone": "+8802223358000",
        "alternate_phone": "+8801320036600",
        "latitude": 23.7099,
        "longitude": 90.4116,
        "source": "DMP Lalbagh Division",
        "source_url": "https://dmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    # --- FIRE SERVICE & CIVIL DEFENCE ---
    {
        "name": "Fire Service & Civil Defence National HQ",
        "name_bn": "ফায়ার সার্ভিস ও সিভিল ডিফেন্স অধিদপ্তর",
        "service_type": ServiceType.FIRE_SERVICE,
        "district": "Dhaka",
        "area": "Siddique Bazar",
        "address": "Kazi Alauddin Road, Siddique Bazar, Dhaka-1000",
        "address_bn": "কাজী আলাউদ্দিন রোড, সিদ্দিক বাজার, ঢাকা-১০০০",
        "phone": "+8802223355555",
        "alternate_phone": "16163",
        "latitude": 23.7226,
        "longitude": 90.4082,
        "source": "Bangladesh Fire Service & Civil Defence Official Portal",
        "source_url": "https://fireservice.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "Tejgaon Fire Station",
        "name_bn": "তেজগাঁও ফায়ার স্টেশন",
        "service_type": ServiceType.FIRE_SERVICE,
        "district": "Dhaka",
        "area": "Tejgaon",
        "address": "Shaheed Tajuddin Ahmed Avenue, Tejgaon, Dhaka",
        "address_bn": "শহীদ তাজউদ্দীন আহমদ সরণি, তেজগাঁও, ঢাকা",
        "phone": "+88029114444",
        "alternate_phone": "16163",
        "latitude": 23.7661,
        "longitude": 90.3992,
        "source": "Bangladesh Fire Service",
        "source_url": "https://fireservice.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    # --- CHITTAGONG METROPOLITAN (CMP) ---
    {
        "name": "Chittagong Kotwali Model Police Station",
        "name_bn": "কোতোয়ালী মডেল থানা (চট্টগ্রাম)",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Chittagong",
        "area": "Kotwali",
        "address": "KC Dey Road, Kotwali, Chittagong",
        "address_bn": "কে সি দে রোড, কোতোয়ালী, চট্টগ্রাম",
        "phone": "+88031619922",
        "alternate_phone": "+8801320107800",
        "latitude": 22.3364,
        "longitude": 91.8340,
        "source": "Chittagong Metropolitan Police (CMP)",
        "source_url": "https://cmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    {
        "name": "GEC Circle Police Box",
        "name_bn": "জিইসি মোড় পুলিশ বক্স",
        "service_type": ServiceType.POLICE_BOX,
        "district": "Chittagong",
        "area": "GEC",
        "address": "GEC Circle, CDA Avenue, Nasirabad, Chittagong",
        "address_bn": "জিইসি মোড়, সিডিএ এভিনিউ, নাসিরাবাদ, চট্টগ্রাম",
        "phone": "+8801320107815",
        "alternate_phone": "999",
        "latitude": 22.3589,
        "longitude": 91.8219,
        "source": "CMP Traffic Division",
        "source_url": "https://cmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    # --- SYLHET METROPOLITAN (SMP) ---
    {
        "name": "Sylhet Kotwali Model Police Station",
        "name_bn": "কোতোয়ালী মডেল থানা (সিলেট)",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Sylhet",
        "area": "Kotwali",
        "address": "Court Road, Bandar Bazar, Sylhet",
        "address_bn": "কোর্ট রোড, বন্দর বাজার, সিলেট",
        "phone": "+880821716942",
        "alternate_phone": "+8801320117800",
        "latitude": 24.8917,
        "longitude": 91.8710,
        "source": "Sylhet Metropolitan Police (SMP)",
        "source_url": "https://smp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    # --- RAJSHAHI METROPOLITAN (RMP) ---
    {
        "name": "Rajshahi Boalia Model Police Station",
        "name_bn": "বোয়ালিয়া মডেল থানা (রাজশাহী)",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Rajshahi",
        "area": "Boalia",
        "address": "Rani Bazar, Boalia, Rajshahi",
        "address_bn": "রাণী বাজার, বোয়ালিয়া, রাজশাহী",
        "phone": "+880721770011",
        "alternate_phone": "+8801320127800",
        "latitude": 24.3685,
        "longitude": 88.6042,
        "source": "Rajshahi Metropolitan Police (RMP)",
        "source_url": "https://rmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
    # --- KHULNA METROPOLITAN (KMP) ---
    {
        "name": "Khulna Sadar Police Station",
        "name_bn": "খুলনা সদর থানা",
        "service_type": ServiceType.POLICE_STATION,
        "district": "Khulna",
        "area": "Khulna Sadar",
        "address": "South Central Road, Khulna Sadar, Khulna",
        "address_bn": "সাউথ সেন্ট্রাল রোড, খুলনা সদর, খুলনা",
        "phone": "+88041720233",
        "alternate_phone": "+8801320137800",
        "latitude": 22.8122,
        "longitude": 89.5644,
        "source": "Khulna Metropolitan Police (KMP)",
        "source_url": "https://kmp.gov.bd",
        "verification_status": VerificationStatus.VERIFIED,
    },
]


async def seed_emergency_services(session: AsyncSession) -> int:
    """Inserts or updates verified official emergency services directory."""
    seeded_count = 0
    now = datetime.now(timezone.utc)

    for item in OFFICIAL_EMERGENCY_SERVICES:
        stmt = select(EmergencyService).where(
            EmergencyService.name == item["name"],
            EmergencyService.district == item["district"],
        )
        res = await session.execute(stmt)
        existing = res.scalar_one_or_none()

        if existing:
            existing.name_bn = item.get("name_bn")
            existing.service_type = item["service_type"]
            existing.area = item["area"]
            existing.address = item["address"]
            existing.address_bn = item.get("address_bn")
            existing.phone = item["phone"]
            existing.alternate_phone = item.get("alternate_phone")
            existing.latitude = item["latitude"]
            existing.longitude = item["longitude"]
            existing.source = item.get("source", existing.source)
            existing.source_url = item.get("source_url")
            existing.verification_status = item.get("verification_status", VerificationStatus.VERIFIED)
            existing.last_verified_at = now
            existing.is_active = True
        else:
            service = EmergencyService(
                name=item["name"],
                name_bn=item.get("name_bn"),
                service_type=item["service_type"],
                district=item["district"],
                area=item["area"],
                address=item["address"],
                address_bn=item.get("address_bn"),
                phone=item["phone"],
                alternate_phone=item.get("alternate_phone"),
                latitude=item["latitude"],
                longitude=item["longitude"],
                source=item.get("source", "Official Bangladesh Police Directory"),
                source_url=item.get("source_url"),
                verification_status=item.get("verification_status", VerificationStatus.VERIFIED),
                last_verified_at=now,
                is_active=True,
            )
            session.add(service)
            seeded_count += 1

    await session.commit()
    logger.info(f"Successfully processed {len(OFFICIAL_EMERGENCY_SERVICES)} emergency services ({seeded_count} newly inserted).")
    return len(OFFICIAL_EMERGENCY_SERVICES)


async def main():
    async with async_session_factory() as session:
        await seed_emergency_services(session)


if __name__ == "__main__":
    asyncio.run(main())
